theme: jekyll-theme-minimal
title: "Updated Map of Doñana National Park (V1.0, 2026)"
description: "With special attention to its ponds, marsh, toponyms and vernaculars."

menu:
  - label: "Home - Inicio"
    url: "/"
  - label: "English"
    url: "/en/"
  - label: "Español"
    url: "/es/"
  - label: "Download data - Descarga de datos"
    url: "https://doi.org/10.5281/zenodo.18109683"
  - label: "Acknowledgements - Agradecimientos"
    url: "/acknowledgement/"
  - label: "Contact - Contacto"
    url: "/contact/"

links:
  - label: "Google Scholar"
    url: "https://scholar.google.com/citations?user=JQzRGw4AAAAJ&hl=es"
  - label: "Contact me/ Contáctame"
    url: "mailto:m.defelipe.t@gmail.com"

citation_label: "Cita recomendada:"
citation_text: "M. de Felipe (2026). Mapa actualizado del Parque Nacional de Doñana (v1.0). Zenodo."
citation_doi_label: "DOI: [DOI]"
citation_doi_url: "https://doi.org/10.5281/zenodo.18109683"
